version: "3.9"
services:

  api:
    build: ./api
    ports:
      - "3000:3000"
      
  db:
    image: "postgres:latest"
    restart: always
    environment: 
      POSTGRES_USER: 
      POSTGRES_PASSWORD:
      POSTGRES_DB:      