version: "3.9"
services:

  api:
    build: .
    environment:
      POSTGRES_CONNECTION_STRING: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}"
    ports:
      - "3000:3000"
      
  db:
    image: "postgres:latest"
    restart: always
    environment: 
      POSTGRES_USER: 
      POSTGRES_PASSWORD:
      POSTGRES_DB:    