version: "3.9"
services:

  api:
    build: ./api
    environment:
      POSTGRES_CONNECTION_STRING: "postgres://user:password@db:5432/postgres"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      
  db:
    image: "postgres:latest"
    restart: always
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5