# This is a basic workflow to help you get started with Actions

name: deployFlow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  
env:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: database

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build docker containers
        run: docker-compose build 
      
      - name: run docker containers
        run: docker-compose up -d
      
      - name: run npm install
        run: |
          cd api
          npm ci
          
      - name: run tests
        run: |
          cd api
          npm run test-ci

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build
        run: docker-compose build
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: publish
        run: docker-compose push
